# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0015_auto_20170129_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
