# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0016_auto_20170201_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
