# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 04:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0017_auto_20170201_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date created'),
        ),
    ]
