# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0018_chef_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='email',
            field=models.CharField(default='none', max_length=50, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='first_name',
            field=models.CharField(default='none', max_length=30, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='last_name',
            field=models.CharField(default='none', max_length=30, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
