# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0022_auto_20170201_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos'),
        ),
        migrations.AddField(
            model_name='dish',
            name='photo_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Photo comment'),
        ),
    ]
