# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0023_auto_20170202_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('dishtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('dishtype_tag', models.CharField(max_length=30, verbose_name='Dish type tag')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date created')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type_tag',
            field=models.ManyToManyField(to='cooklog.DishType'),
        ),
    ]
