# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0024_auto_20170706_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_type_tag',
        ),
        migrations.AddField(
            model_name='dish',
            name='dishtype_id',
            field=models.ManyToManyField(blank=True, to='cooklog.DishType'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient_id',
            field=models.ManyToManyField(blank=True, to='cooklog.Ingredient'),
        ),
    ]
