# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0025_auto_20170706_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('ingredient_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_type_name', models.CharField(max_length=30, verbose_name='Ingredient type name')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('maker_id', models.AutoField(primary_key=True, serialize=False)),
                ('maker_name', models.CharField(max_length=30, verbose_name='Maker name')),
                ('maker_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Maker type')),
                ('maker_url', models.URLField(blank=True, null=True, verbose_name='Ingredient URL')),
                ('maker_image', models.ImageField(blank=True, null=True, upload_to='maker_photos')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_type',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_photos'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type_detail',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ingredient type detail'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ingredient URL'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_method',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Dish method'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooklog.IngredientType'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooklog.Maker'),
        ),
    ]
