# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0027_cheffollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheffollows',
            old_name='user_id',
            new_name='follower_id',
        ),
    ]
