# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0028_auto_20170728_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheffollows',
            name='chef_id',
        ),
        migrations.AddField(
            model_name='cheffollows',
            name='chef_id',
            field=models.ManyToManyField(related_name='followed_by', to='cooklog.Chef'),
        ),
    ]
