# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 02:28
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0029_auto_20170731_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheffollows',
            name='chef_follow_id',
        ),
        migrations.AddField(
            model_name='cheffollows',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheffollows',
            name='follower_id',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
