# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0030_auto_20170731_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('recipecategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipecategory_name', models.CharField(max_length=30, verbose_name='Recipe category name')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish_photo',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dishtype_id',
        ),
        migrations.DeleteModel(
            name='Dish_Photo',
        ),
        migrations.DeleteModel(
            name='DishType',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipecategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooklog.RecipeCategory'),
        ),
    ]
